services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: collateral
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  collateral-service:
    build: ./collateral-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/collateral
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  pricing-service:
    build: ./pricing-service
    ports:
      - "8081:8080"

  trade-service:
    build: ./trade-service
    depends_on:
      - pricing-service
      - postgres
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/collateral
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  api-gateway:
    build: ./api-gateway
    depends_on:
      - trade-service
      - pricing-service
      - collateral-service
    ports:
      - "8085:8080"

volumes:
  postgres_data: