spring:
  cloud:
    gateway:
      routes:

        - id: pricing-service
          uri: http://pricing-service:8080
          predicates:
            - Path=/pricing/**

        - id: trade-service
          uri: http://trade-service:8080
          predicates:
            - Path=/trade/**

        - id: collateral-service
          uri: http://collateral-service:8080
          predicates:
            - Path=/collateral/**