apiVersion: apps/v1
kind: Deployment
metadata:
  name: collateral-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collateral-service
  template:
    metadata:
      labels:
        app: collateral-service
    spec:
      containers:
        - name: collateral-service
          image: javisaizengineer/collateral-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080