name: Collateral Service CI

on:
  push:
    paths:
      - "collateral-service/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: |
          cd collateral-service
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build -t javisaizengineer/collateral-service:${{ github.run_number }} ./collateral-service
          docker push javisaizengineer/collateral-service:${{ github.run_number }}